repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: poetry run black src tests
        pass_filenames: false
        language: system
      - id: mypy
        name: mypy
        entry: poetry run mypy src tests
        pass_filenames: false
        language: system
      - id: flake8
        name: flake8
        entry: poetry run flake8 src tests
        pass_filenames: false
        language: system
      - id: pytest
        name: pytest
        entry: poetry run pytest
        pass_filenames: false
        language: system